Text gen tensorflow (Not Working)/__init__.py
from flask import Flask
from .routes import generator


def create_app(config_file='settings.py'):
    app = Flask(__name__, static_url_path="/tmp", static_folder="tmp")

    app.config.from_pyfile(config_file)

    app.register_blueprint(generator)
    return app





Text gen tensorflow (Not Working)/routes.py
from flask import Blueprint, render_template, request, redirect
# from .generator import ai

generator = Blueprint('generator', __name__)

@generator.route('/')
def index():
    return render_template('index.html')

@generator.route('/analyze', methods=['POST'])
def analyze():
    title = request.form['title']
    text = ai.generate_text(title)

    return render_template('index.html', text=text)



Text gen tensorflow (Not Working)/templates/index.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
<div>

<div>
<form style="max-width: 800px; margin: 50px; justify-self: center;" methods="POST" action="{{url_for('generator.analyze')}}">
<div class="form-group">
<label for="title" style="font-size: 33px;">Title</label>
<input type="text" style="heigth: 60px; font-size: 20px;" class="form-control" placeholder="Enter Text" name="title"/>
</div>

<button type="submit" class="btn btn-primary">Submit</button>
</form>

<p class="text-left" style="cursor: pointer; margin: 50px; padding: 10px; font-size: 24px;">
   OpenAI: {{ text }}
</p>

</div>

<div>
   <img style="margin: 10px;" alt="Wal"  src="../tmp/gaich.jpg"/>
</div>



</div>